/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface ConfidentialVotingInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "confidentialProtocolId"
      | "encryptedTallies"
      | "isTallyFinalized"
      | "proposalVotes"
      | "requestTallyDecryption"
      | "submitEncryptedVote"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "TallyDecryptRequested" | "VoteSubmitted"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "confidentialProtocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "encryptedTallies",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isTallyFinalized",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "proposalVotes",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "requestTallyDecryption",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "submitEncryptedVote",
    values: [BigNumberish, BytesLike, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "confidentialProtocolId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "encryptedTallies",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isTallyFinalized",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "proposalVotes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestTallyDecryption",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitEncryptedVote",
    data: BytesLike
  ): Result;
}

export namespace TallyDecryptRequestedEvent {
  export type InputTuple = [proposalId: BigNumberish];
  export type OutputTuple = [proposalId: bigint];
  export interface OutputObject {
    proposalId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VoteSubmittedEvent {
  export type InputTuple = [proposalId: BigNumberish, voter: AddressLike];
  export type OutputTuple = [proposalId: bigint, voter: string];
  export interface OutputObject {
    proposalId: bigint;
    voter: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ConfidentialVoting extends BaseContract {
  connect(runner?: ContractRunner | null): ConfidentialVoting;
  waitForDeployment(): Promise<this>;

  interface: ConfidentialVotingInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  confidentialProtocolId: TypedContractMethod<[], [bigint], "view">;

  encryptedTallies: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  isTallyFinalized: TypedContractMethod<
    [arg0: BigNumberish],
    [boolean],
    "view"
  >;

  proposalVotes: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [[boolean, string] & { exists: boolean; encryptedVote: string }],
    "view"
  >;

  requestTallyDecryption: TypedContractMethod<
    [proposalId: BigNumberish],
    [void],
    "nonpayable"
  >;

  submitEncryptedVote: TypedContractMethod<
    [proposalId: BigNumberish, encryptedVote: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "confidentialProtocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "encryptedTallies"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "isTallyFinalized"
  ): TypedContractMethod<[arg0: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "proposalVotes"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [[boolean, string] & { exists: boolean; encryptedVote: string }],
    "view"
  >;
  getFunction(
    nameOrSignature: "requestTallyDecryption"
  ): TypedContractMethod<[proposalId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "submitEncryptedVote"
  ): TypedContractMethod<
    [proposalId: BigNumberish, encryptedVote: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "TallyDecryptRequested"
  ): TypedContractEvent<
    TallyDecryptRequestedEvent.InputTuple,
    TallyDecryptRequestedEvent.OutputTuple,
    TallyDecryptRequestedEvent.OutputObject
  >;
  getEvent(
    key: "VoteSubmitted"
  ): TypedContractEvent<
    VoteSubmittedEvent.InputTuple,
    VoteSubmittedEvent.OutputTuple,
    VoteSubmittedEvent.OutputObject
  >;

  filters: {
    "TallyDecryptRequested(uint256)": TypedContractEvent<
      TallyDecryptRequestedEvent.InputTuple,
      TallyDecryptRequestedEvent.OutputTuple,
      TallyDecryptRequestedEvent.OutputObject
    >;
    TallyDecryptRequested: TypedContractEvent<
      TallyDecryptRequestedEvent.InputTuple,
      TallyDecryptRequestedEvent.OutputTuple,
      TallyDecryptRequestedEvent.OutputObject
    >;

    "VoteSubmitted(uint256,address)": TypedContractEvent<
      VoteSubmittedEvent.InputTuple,
      VoteSubmittedEvent.OutputTuple,
      VoteSubmittedEvent.OutputObject
    >;
    VoteSubmitted: TypedContractEvent<
      VoteSubmittedEvent.InputTuple,
      VoteSubmittedEvent.OutputTuple,
      VoteSubmittedEvent.OutputObject
    >;
  };
}
